### ISSUE TITLE
Request to access the complete dataset

### ISSUE THREAD

**Issue by Harper-Hua** [weipang142857/ClavaDDPM#1]
Hello,

In the paper, you mentioned there are 5 datasets in total while in this repo only 2 are provided. I'd like to kindly request the access to the complete dataset. Thank you!

**Comment by weipang142857** [comment]
Hi, the link to the other datasets are updated in the README.

**Comment by Harper-Hua** [comment]
Hi there!

Thank you so much for the update! Wondering if you could also upload the config files for other datasets like configs/ccs.json. Thanks

**Comment by weipang142857** [comment]
> Hi there!
> 
> Thank you so much for the update! Wondering if you could also upload the config files for other datasets like configs/ccs.json. Thanks

Hi, the config files are updated.
